=== bozzo1337/computer-database/console/src/test/resources/dataset.dtd
<!ELEMENT dataset (
    company*,
    computer*)>

<!ELEMENT company EMPTY>
<!ATTLIST company
    id CDATA #REQUIRED
    name CDATA #IMPLIED
>

<!ELEMENT computer EMPTY>
<!ATTLIST computer
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    introduced CDATA #IMPLIED
    discontinued CDATA #IMPLIED
    company_id CDATA #IMPLIED
>

=== bozzo1337/computer-database/src/test/resources/dataset.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataset.dtd">
<dataset>
	<company id="1" name="Company1"/>
	<company id="2" name="Company2"/>
	<company id="4" name="Company4"/>
	<company id="5" name="Company5"/>
	<computer id="1" name="Computer1" introduced="2010-10-10"
		discontinued="2010-10-12" company_id="1"/>
	<computer id="3" name="Computer3" introduced="1989-12-05"
		discontinued="2010-10-12" />
	<computer id="22" name="Computer22"/>
	<computer id="18" name="Computer18" company_id="1"/>
	<computer id="15" name="Computer15" introduced="1999-09-06"
		company_id="5"/>
	<computer id="999" name="Computer999" introduced="1980-11-11"
		discontinued="2099-01-01" company_id="5"/>
	<computer id="44" name="Computer44" introduced="1970-01-01"
		discontinued="2070-01-01" company_id="4"/>
	<computer id="42" name="Computer42"
		discontinued="2000-03-03" company_id="2"/>
</dataset>
